# Generated by Django 5.0.6 on 2024-07-02 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='uploads/profiles')),
                ('headline', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChirpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='uploads/images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermodel')),
            ],
        ),
    ]
