# Generated by Django 5.0.6 on 2024-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirpmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
