# Generated by Django 5.0.6 on 2024-07-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_chirpmodel_likes_delete_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirpmodel',
            name='likes',
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chirp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.chirpmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
